### ISSUE TITLE
EXP bugs.

### ISSUE THREAD

**Issue by Lapis2** [ApexKO/issue-tracking#17]
- [x] EXP % doesn't update at the bottom. I'm stuck at 2.53 and won't move (has something to do with the exp seal, if I turn it on and off it updates, but it won't update in real time as I get more exp from monsters)

 - [x] Machirodus and Saber Tooth give pitiful exp (427), same with Sheriffs (1500) while Blood dons give 35k, I assume most of the exp rates are broken.

**Comment by twostars** [comment]
Closing this. If the former bug is still observed, a specific issue should be created for it.
