### ISSUE TITLE
Jamadar defense necklace and belt won't drop from Monster stone.

### ISSUE THREAD

**Issue by Lapis2** [ApexKO/issue-tracking#183]
These 2 have 8 of defense against each weapon except dagger (instead they have jamadar)

not really worth using and bad, but they're supposed to be in the boss drop table.

**Comment by maxmenten** [comment]
This is pending a re-import of item data from the (special) item tbls, as these old uniques are currently not in the database.

**Comment by twostars** [comment]
Item importer was fixed to allow for these cases, these items are now imported into the database. Just need to setup the drops now!

**Comment by aesteris** [comment]
This is now done, closing this!
