### ISSUE TITLE
Implement support for Nereids updates

### ISSUE THREAD

**Issue by twostars** [ApexKO/issue-tracking#333]
- [x] Timer.
 - [x] Monument status list.
 - [x] Monument capture updates.
 - [x] Supplies updates.
 - [x] Point requests.

**Comment by twostars** [comment]
Changed this issue to be slightly more encompassing. We've reversed the updates needed here, so they just need to be implemented.

**Comment by aesteris** [comment]
Support for these has been implemented and tested, whether the logic (e.g. even if you kill a monument it doesn't count until 15 minutes in) is correct is something we'd need to hear from the players. Closing this now.
