### ISSUE TITLE
Orc Bandit leader AoE range is too small.

### ISSUE THREAD

**Issue by Lapis2** [ApexKO/issue-tracking#348]
From this range I am already be safe from his AoE currently in alpha: http://puu.sh/diHOO/21d9415a51.jpg (a single step closer and I'd be affected by it)

Needs to be 33% more of that distance (corrected).

Also, from that range I could safely range-attack them and OBL wouldn't do anything about it (other than AoEing himself like an idiot: http://puu.sh/diHVy/b4e046fcb7.jpg). 

OBL should actively try to run up to people attacking him from out of his AoE range, in order to get into AoE range. Not just stare from afar attacking himself.

His AoE mana drain cast rate is also too quick: Takes place 2 times per second when it should be every 1.5 - 2.0 seconds, like Atross.

**Comment by Lapis2** [comment]
Yeah he's kinda messed up... he should behave like Atross is right now, identically. Atross is perfect.

Perhaps with a little more range to its aoe, but other than that it'd be great.

**Comment by maxmenten** [comment]
These issues should all be resolved next restart, he now behaves similar to Atross, attacks slower, and moves a little slower too!
