### ISSUE TITLE
Chaos issues I found

### ISSUE THREAD

**Issue by Lapis2** [ApexKO/issue-tracking#358]
- [x] No 5k damage saw blades... I like it better this way, but I thought I'd mention it (twostars: these are intended to spawn, and do actually spawn on our local servers, so this is indeed unusual).
- [x] Chaos cubes sometimes grant multiple items.
- [x] No matter what rank I was in chaos, I only got Light Feet from the cubes.
- [x] Projectiles do not persist after death. If I throw an Ice Sword or Poison Knife right before I die, they whiff and disappear while flying to their target (skill goes on cd).
- [x] I was second to last (bottom 25%) yet I received everything that a top 25% should've gotten (blue chest, voucher of oracle)

**Comment by maxmenten** [comment]
The saw blades are no longer disappearing; the only thing missing at the moment is them dealing 5k damage upon hitting someone.

**Comment by maxmenten** [comment]
Closing this as it only requires the saw blades to deal 5k damage when hitting someone; need to handle this differently.
