### ISSUE TITLE
Daily ladder rank wings

### ISSUE THREAD

**Issue by twostars** [ApexKO/issue-tracking#393]
No idea what the state of these are, I'd assume they're not implemented whatsoever but if they are, they may be broken or at the very least flawed. If it works on ladder rankings, then we need to be sure they can only obtain it once per day, similarly to stipends.

**Comment by maxmenten** [comment]
There's 5 different wings here;

1. King's wing (no idea which one that is)
2. War wing (for those killing the opponent nation's keeper)
3. War wing (for those killing the opponent nation's warder 1)
4. War wing (for those killing the opponent nation's warder 2)
5. Ladder (for those holding the ladder dragon symbol that day)
