### ISSUE TITLE
[Juraid] Minotaur can randomly kill you by applying over 40 instances of its DoT in 1 second.

### ISSUE THREAD

**Issue by Lapis2** [ApexKO/issue-tracking#458]
Idk, he suddenly gets bored of applying 1 stack per acid pot-ish thingy and then boom.

http://puu.sh/dD9z6/e2ee79bd5e.jpg

Not sure if this also applies to other monsters with DoT's (bone dragon, lirimu)

**Comment by maxmenten** [comment]
I've been tanking a minotaur for the past 10 minutes in hopes it'd do the same to me, it didn't however. Labeling this *nix-specific, pending verification on either Alpha or a *nix local server.

**Comment by Lapis2** [comment]
Oh, didn't cross my mind to mention that this happened only when I was running away from it / moving in circles.

I was not tanking his melee attack. I was getting showered by his dot.

**Comment by maxmenten** [comment]
I've done this in my test too, first tank just his acid potion like DoT while standing still, then when kiting him around. Neither of them reproduced a truckload of DoT ticks (or casts, for that matter).

**Comment by Lapis2** [comment]
Strange... I'll assume this was solved then.

**Comment by twostars** [comment]
Need to re-test it, but I'd be inclined to believe it was a result of the timer bug, hence my earlier commit. :)

**Comment by maxmenten** [comment]
It's been retested and it's been deemed fixed.
