### ISSUE TITLE
[Mage] Double Blink fails when casted too quickly (instantly magic stuff)

### ISSUE THREAD

**Issue by Lapis2** [ApexKO/issue-tracking#521]
Goes on CD, consumed MP and you don't move an inch.

First one works, second one doesn't.

http://puu.sh/dM3fL/b065494ebf.jpg

Skills involved:
Master 15 points: Instantly magic
Blitz 80 points: Blink

**Comment by maxmenten** [comment]
Will close this for now as this can't be reliably reproduced, once anyone's able to reproduce (consistently) don't hesitate to re-open it with instructions on how to do it.
