### ISSUE TITLE
[CZ Chaos stone] Bosses not dealing enough damage.

### ISSUE THREAD

**Issue by Lapis2** [ApexKO/issue-tracking#547]
Chaos stone monsters are supposed to deal really high amounts of damage while being extra tanky, even if they share the name with other bosses known for being weak and squishy.

Every single boss that comes from the chaos stone (with the exception of Bach, Duke and Bishop) should deal upwards of 1000 damage... perhaps up to 1600 if you're a paper mage or something (these numbers are after the 70 passive).

Right now they're tanky which is fine, and I believe Dulian, Query and Jersey hit harder than the other bosses. If Dulian and co. serve as a good indicator for damage, I would slightly increase it over that value.

**Comment by maxmenten** [comment]
This was done; pending a restart.
