### ISSUE TITLE
Kurian's level 66 skill doesn't deal more damage than it's level 51 counter part

### ISSUE THREAD

**Issue by maxmenten** [ApexKO/issue-tracking#548]

**Comment by twostars** [comment]
Did you find this yourself (on your local server), or was it reported? I set all these damages, and these skills seem to be dealing the correct damage to me -- you probably just haven't run the script to apply all the skill tweaks.

**Comment by maxmenten** [comment]
The problem was with the 'Hit' column in magic_type1 not being set to 100; and thus the level 66 'base component' of the skill barely did any damage. This is fixed pending a restart.
