### ISSUE TITLE
Cardinal issues

### ISSUE THREAD

**Issue by maxmenten** [ApexKO/issue-tracking#549]
- [x] Cardinals in CZ aren't using their 'poison' skills.
- [x] EMC and Elmorad side CZ Cardinals should only drop Asga fruit.
- [x] Luferson and Karus side CZ Cardinals should only drop Cardinal jewels.

**Comment by Woipa** [comment]
nonono, you got it wrong, cardinal jewels are for luff+ karus side of CZ, asga fruit is for emc+ elmorad side of CZ

**Comment by maxmenten** [comment]
Changed the description for those 2 to how they should be

**Comment by maxmenten** [comment]
These issues are now fixed, pending a restart.
