### ISSUE TITLE
Nereids War spawns

### ISSUE THREAD

**Issue by maxmenten** [ApexKO/issue-tracking#553]
These are currently missing preventing us from testing Nereids.

- [x] Warders and Keepers
- [x] Victory Gates
- [x] Monuments
- [x] Supplies (Wannigan)

**Comment by maxmenten** [comment]
Warders / Keepers, and Victory Gates have been added;

**Comment by maxmenten** [comment]
Unsure of the supplies name, would like to know this to be able to spawn a few!

**Comment by twostars** [comment]
This should be updated now that we know the name.

**Comment by maxmenten** [comment]
They've been added to the DB and put on a random spawn rotation. Closing this now!
