### ISSUE TITLE
Quest issues / NPC dialog issues.

### ISSUE THREAD

**Issue by maxmenten** [ApexKO/issue-tracking#56]
Please report any issues regarding quests / npc dialog here. (not in seperate issues!)

- [x] Boatman in Ronark Land
- [x] [Grand Merchant] Kaishan
- [x] [White Shadow Captain] Sirin
- [x] [VIP Manager] Juliane
- [x] [Manager] Bilbor
- [x] \<nation\> Hero Statue (not working in USKO)

**Comment by twostars** [comment]
I really can't help but feel these should be separate issues, especially for the NPCs that handle a lot of different functionality.

**Comment by maxmenten** [comment]
The hero statues don't do anything on USKO currently, trying to figure out what they're supposed to do and otherwise we'll consider those to be scriptless.
