### ISSUE TITLE
Quests: Abandoning quests doesn't always fully abandon them

### ISSUE THREAD

**Issue by maxmenten** [ApexKO/issue-tracking#569]
You can abandon them, but after you RELOG they are back in "quest tips" (cant see them in max/seed though). When you click on them in the quest tips, you will get these options: http://i.imgur.com/Aahd87g.jpg, then you hit accept and get this http://i.imgur.com/pRcXZD7.jpg , hitting abandon wont do anything

**Comment by twostars** [comment]
Fixed.
