### ISSUE TITLE
Zone channels/instances during invasions

### ISSUE THREAD

**Issue by twostars** [ApexKO/issue-tracking#608]
Now that players can change to alternate channels (instances) of a select few zones, we foresee an issue with war invasions for El Morad/Luferson zones.

It seems officially there's some errors regarding this, so in all likelihood they disable it during wars (I'm not too sure, though), but I'm not a huge fan of this. If there's too many people in there already, where are they going to go? Be kicked out to Moradon for no real reason?

Instead, it might be preferable to allow the invasion... but ONLY in instance 1. Instances 2 & 3 will continue to behave as normal, and the opposing nation will not be able to enter them.

Right now all the instances work the same with the monuments etc -- so you could effectively jump instances to take all the monuments... not good!

 - [x] Block entry to El Morad/Luferson instances from the opposing nation.
 - [x] Tell the client there's no available instances for the opposing nation's zone, so the instance menu isn't even displayed in the first place.
 - [x] Disable monument "capturing" (deaths) in instances 2 & 3.
 - [ ] Warn players in instances 2 & 3 of home zones that they'll be kicked out when the war starts, at the same time as the "X minutes left before war begins" notice.
 - [x] People will then be kicked out of 2 & 3 as war starts (not invasion).
 - [x] People that were kicked will spawn in instance 1, in the same exact place where they were in 2 & 3.
 - [x] Accessing 2 & 3 in midst of a war is impossible for either nation.
 - [x] After the invasion ends, access to instances will be restored.
 - [x] Ensure we block automatic overflow into other instances when the main instance is full.

**Comment by Lapis2** [comment]
Is it really a good idea to support multiple instances in home maps? Invasions don't really feel like a penalty /disadvantage if people can simply jump to other copies of their home map.

**Comment by twostars** [comment]
What would we do with the other instances when an invasion starts?

**Comment by Lapis2** [comment]
Why even have instances anywhere other than in eslant / moradon? Or is this how it works officially o_O?

**Comment by twostars** [comment]
The zones we can instance (or well, have a special menu for to let players jump around into different instances with) are the only ones defined officially. We can't actually deal with any other zones like this.

I'm really not sure how official deals with this zone. All I know is there's a couple of errors in there stating:
You cannot change to a different instance while in the war.
You cannot change to a different instance while attacking enemy country.

**Comment by Lapis2** [comment]
So the instances can't just be removed from main towns?

Moradon and eslant instancing (idk if it's supported) makes sense because on release and for general EXPing its good to have multiple spots available. But instances for EMC or Luferson don't really add up imho, there's just no point in splitting the already few people leveling there.

If it can't be helped then leaving like it is wouldn't matter really, I was just stating how "invading" lost a whole lot of meaning if people can just keep exping in other instance as if nothing happened. Just one small quirk regarding being able to hunt down noobs because that has always been a trademark of invasions for most people :P

**Comment by Lapis2** [comment]
To summarize:
1. Instances will stay for main towns (1, 2, 3)
2. There will be warnings that come along with the "X minutes left before war begins".
3. People will then be kicked out of 2 & 3 as war starts (not invasion).
4. People that were kicked will spawn in instance 1, in the same exact place where they were in 2&3.
5. Accessing 2 & 3 in midst of a war is impossible for either nation.
6. After the invasion ends, access to instances will be restored.

I think that's pretty much what you said anyway, sounds good!

**Comment by twostars** [comment]
This is mostly done, there's just no warnings before the wars, so nothing I could do in that regard. I forget how that even works officially, but couldn't find any official resources similar to that. I think the client's scheduler handles this now.

I can add a warning, but the easiest way to do that is to queue it for like 5 minutes after the war starts, and just start warning them when the war starts. Since it's not the invasion stage, this still isn't a problem... unless the war is won within 5 minutes (which I don't think is going to happen, ever, unless there's some serious speedhacking involved -- which isn't really possible at this point).
