### ISSUE TITLE
Kurian/Porutu "Spirit strengthening" skill doesn't appear to work

### ISSUE THREAD

**Issue by twostars** [ApexKO/issue-tracking#653]
This skill is intended to boost heals & reduce mana consumption.

It *is* implemented, and was working previously...

http://forum.apexko.com/topic/397-portu-skill-doesnt-work/

**Comment by aesteris** [comment]
Seems as if the reporter jumped the gun, only potions weren't boosting (and have since been changed to do so). Mana cost reduction and healing increase on skills have always been working (double checked for both unmastered and mastered porutu for both nations).
