### ISSUE TITLE
EXP/DC/WAR flashes not working

### ISSUE THREAD

**Issue by twostars** [ApexKO/issue-tracking#658]
They don't appear to do anything other than remove the item and show the use effect. I'm not sure if there's meant to be a visual indicator otherwise.

**Comment by twostars** [comment]
Ah, they do work, but they have no duration so they're expiring instantly. I'm not sure how these work officially in that regard.

**Comment by Lapis2** [comment]
They are removed when you disconnect or level up. About 90% sure they're also removed on death and zone changes.

Duration wise... I think they're permanent (or until one of the above happen). Would need the input of a current USKO player.
